databases:
  - name: recipe-app-db
    databaseName: recipe_app_database
    user: recipe_app_user
services:
  - type: web
    name: recipe-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
